from __future__ import annotations

from pathlib import Path

DEFAULTS_DIR = Path(__file__).resolve().parent
DEFAULT_PRIMER_LIST_NAME = "default_primers.txt"
DEFAULT_PRIMER_LIST_PATH = DEFAULTS_DIR / DEFAULT_PRIMER_LIST_NAME
DEFAULT_OUTPUT_PRIMER_LIST_PATH = "sanger_primers.txt"
DEFAULT_COVERAGE_REPORT_PATH = "coverage_report.txt"

TARGET_COVERAGE_OPTIONS = (2, 3, 4)
DEFAULT_TARGET_COVERAGE = 2
DEFAULT_MASK_TEXT = ""
MASK_TEXT_PLACEHOLDER = "63..88,3025..3063"
DEFAULT_PRIMER_NAME_PREFIX = "designed"
DELIMITER_OPTIONS = ("tab", "comma", "semicolon")
DEFAULT_DELIMITER_NAME = "tab"
DEFAULT_MAX_ITERATIONS = 200
MAX_ITERATIONS_INPUT_MIN = 1
MAX_ITERATIONS_INPUT_MAX = 500
MAX_ITERATIONS_INPUT_STEP = 10
DEFAULT_USE_DEFAULT_PRIMER_LIST = True

READ_LENGTH = 800
NOISE_LENGTH = 100
EFFECTIVE_READ_LENGTH = READ_LENGTH - NOISE_LENGTH
MIN_PRIMER_LEN = 18
MAX_PRIMER_LEN = 25
MIN_TM = 55.0
MAX_TM = 65.0
MIN_GC = 40.0
MAX_GC = 60.0
MIN_BINDING_GAP = 150
PREFERRED_PAIR_MIN = 300
PREFERRED_PAIR_MAX = 400

DESIGN_BEAM_WIDTH = 12
DESIGN_REGIONS_PER_STATE = 2
DESIGN_OPTIONS_PER_STATE = 10
DESIGN_OPTIONS_PER_REGION = 6
DESIGN_DIVERSE_POSITION_GAP = 75
